general:
  language: default
  language-save: false
  debug: false
chat:
  format: '&2%prefix%a2%player%&e: %message%'
name-tag:
  enable: true
  format: '&a%prefix%&6%player%'
display-name:
  enable: true
  strip-colors: false
group:
  scan-subgroups: true
  format:
    default:
      chat: '&5[GUEST]&3%player%&a: 6%message%'
    vip:
      chat: '&6[VIP]&4%player%&a: %message%'
      name-tag: '&6[VIP] &4%player%'