name: MultiChat
main: ru.nukkit.multichat.MultiChat
version: "0.0.3"
author: fromgate, nukkit.ru
api: ["1.0.0"]
description: MultiChat - universal chat formater based on MultiPass plugin
depend: [Multipass]
permissions:
  multichat.config:
    descripition: Allows to execute MultiChat commands
    default: op